---
title: "Solution to final challenge"
author: "Naupaka Zimmerman"
date: "April 19, 2015"
output: html_document
---

```{r load libraries-and-data, echo=FALSE, message=FALSE, warning=FALSE}
# Load dplyr for data manipulation
library("dplyr")

# Load knitr so we can use the kable() function to format the table output more 
# nicely in our report below
library("knitr")

# Read in the gapminder tab-delimited data
data.in <- read.table("output/combined_gapMinder.tsv", 
                      sep = "\t", header = TRUE)
```

```{r define-scatterplot-function, echo=FALSE}
# function to make a scatter plot of year by GDP per capita for a given country
country.scatter.plot <- function(country.name){
    # first filter the data to just the desired rows
    data.in %>%
        filter(country == country.name) -> filtered.df

    # then plot those rows
    plot(x = filtered.df$year, 
         y = filtered.df$gdpPercap,
         main = paste("GDP by year in", country.name),
         xlab = "Year",
         ylab = "GDP per capita")
}
```


```{r plot-china-scatter, echo=FALSE}
country.scatter.plot("China")
```

We see a huge increase in per capita GDP in China starting in the 1990s.

```{r plot-cuba-scatter, echo=FALSE}
country.scatter.plot("Cuba")
```

In Cuba, GDP reaches a peak in the 1980s, before becoming much lower in the 1990s, and climbing again after the year 2000.

```{r plot-chile-scatter, echo=FALSE}
country.scatter.plot("Chile")
```

The GDP per capita in Chile increases continually, especially after 1990, like China, but in absolute terms, GDP  in Chile is more than twice as high than in China over the same time period.
}
```

